installation:
  kubernetesProvider: "${kubernetes_provider}"
  calicoNetwork:
    bgp: "Disabled"
    ipPools:
      - cidr: "${pod_cidr}"
        encapsulation: "VXLAN"
        natOutgoing: "Enabled"
        nodeSelector: "all()"
  componentResources:
    - componentName: "Node"
      resourceRequirements:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "300m"
          memory: "256Mi"
    - componentName: "KubeControllers"
      resourceRequirements:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
    - componentName: "Typha"
      resourceRequirements:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
tigeraOperator:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"
